### ISSUE TITLE
2 API endpoints broke after updating to 1.3.4

### ISSUE THREAD

**Issue by Mocem1** [nautobot/nautobot#1828]
### Environment
* Python version: 3.7.3
* Nautobot version: 1.3.4 and probably 1.3.5

After updating to version 1.3.4 the following API endpoints broke. 
- api/virtualization/virtual-machines/
- api/dcim/devices/

The reason why it broke is probably caused by the following change:  https://github.com/nautobot/nautobot/issues/1449

### Steps to Reprod
1. Remove all 'Config Context' in the webinterface
2. Test API endpoints from above.
3. Add 1 simple config context
4. Test API endpoints from above and you will probable receive the following error: 
{"error": "'str' object has no attribute 'items'", "exception": "AttributeError", "nautobot_version": "1.3.4", "python_version": "3.7.3"}

Best regards,
Marco

**Comment by glennmatthews** [comment]
I'm unable to reproduce this error so far via a quick test following the steps you provided. If you can reproduce it consistently, could you please gather and provide a full stack trace (via enabling `settings.DEBUG = True` or similar)?

**Comment by glennmatthews** [comment]
Thanks for the information. It looks like somehow in your case `context` is coming back as a `str` rather than a `dict` as it should be. Can you confirm how you're creating the config context? I can reproduce the issue if I bypass data validation and create an (incorrectly populated) ConfigContext with string `data`, i.e.:

```python
>>> cc = ConfigContext.objects.first()
>>> cc.data="{'foo': 'bar'}"
>>> cc.save()
```

but both the UI and the REST API will normally prevent you from creating such `data`, for example:

![image](https://user-images.githubusercontent.com/5603551/171414209-9f085443-072c-4eda-9e84-0774c32329c1.png)

**Comment by Mocem1** [comment]
To rule out invalid JSONs I was already using the webinterface and removed all existing config contexts. 

This morning I have solved the problem because it is clear that there is something wrong in my instance. With the following steps I have solved the problem. 

1. Export data with dumpdata
2. Updated Nautobot to 1.3.5. 
3. Drop and create new database
4. Removed statuses in the webinterface
5. Imported JSON with Loaddata

Everything is now working as it suppose to do with the config contexts from our git repo. 
Thank you for the help .

Best regards,
Marco
