### ISSUE TITLE
next: AttributeError when viewing Circuit object detail page

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#853]
### Environment
* Python version:
* Nautobot version: 1.2.0a1

### Steps to Reproduce
1. Create a Circuit

### Expected Behavior

Redirect to Circuit detail view page successfully.

### Observed Behavior

```
AttributeError at /circuits/circuits/a4ebc8b1-e5b6-4ac6-97e8-c6e6e19d423e/
'Circuit' object has no attribute 'slug'
```

This appears to be a regression due to #735.
