### ISSUE TITLE
GraphQL single-object endpoints broken

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#1112]
### Environment
* Python version: 3.7
* Nautobot version: 1.2.0-beta1

### Steps to Reproduce
1. Build Nautobot instance of 1.2.0-beta1.
2. Add some sample devices and associated data.
3. Attempt to use the GraphiQL endpoint with a simple query such as:

```
query ($device_id: ID!) {
  device(id: $device_id) {
    hostname: name
  }
}
```

along with one of your device's UUID as the query.

### Expected Behavior
Expect to see the device's hostname returned.

### Observed Behavior
Get error with following:

```
{
  "errors": [
    {
      "message": "'Device' object has no attribute 'only'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "device"
      ]
    }
  ],
  "data": {
    "device": null
  }
}
```

A larger query returns this:

```
{
  "errors": [
    {
      "message": "'Device' object has no attribute 'select_related'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "device"
      ]
    }
  ],
  "data": {
    "device": null
  }
}
```

This appears to be related to optimizations that were done in the core.

**Comment by glennmatthews** [comment]
Probably a regression introduced by #769.

**Comment by glennmatthews** [comment]
Seems to be specifically an issue with "single" queries (e.g. `device` as opposed to `devices`.) The corresponding `devices` query seems to work fine:

```graphql
query ($device_id: String!) {
  devices (id: [$device_id]) {
    hostname: name
  }
}
```
