### ISSUE TITLE
Error when scheduled job runs after upgrading to v1.5.8

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#3169]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.8
* Python version: 3.10
* Database platform, version: Unsure
* Middleware(s): K8s

### Steps to Reproduce
1. In Nautobot <= v1.5.7, create a scheduled job
2. Verify scheduled job runs correctly
3. Upgrade Nautobot to v1.5.8
4. Wait for scheduled job to run again
5. Check celery worker container debug logs for reported error

### Expected Behavior

The scheduled job should run normally.

### Observed Behavior

The celery worker crashes.  Debug output:

```
nautobot-celery [2023-01-26 12:29:42,001: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NautobotFakeRequest' object has no attribute '_user_pk'")
nautobot-celery Traceback (most recent call last):
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
nautobot-celery     self.blueprint.start(self)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
nautobot-celery     step.start(parent)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
nautobot-celery     return self.obj.start()
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
nautobot-celery     blueprint.start(self)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
nautobot-celery     step.start(parent)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 628, in start
nautobot-celery     c.loop(*c.loop_args())
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
nautobot-celery     next(loop)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
nautobot-celery     cb(*cbargs)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 1326, in on_readable
nautobot-celery     self.cycle.on_readable(fileno)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 562, in on_readable
nautobot-celery     chan.handlers[type]()
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 967, in _brpop_read
nautobot-celery     self.connection._deliver(loads(bytes_to_str(item)), dest)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 991, in _deliver
nautobot-celery     callback(message)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 624, in _callback
nautobot-celery     return callback(message)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 626, in _receive_callback
nautobot-celery     return on_m(message) if on_m else self.receive(decoded, message)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 596, in on_task_received
nautobot-celery     strategy(
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/strategy.py", line 207, in task_message_handler
nautobot-celery     handle(req)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/worker.py", line 221, in _process_task_sem
nautobot-celery     return self._quick_acquire(self._process_task, req)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/semaphore.py", line 54, in acquire
nautobot-celery     callback(*partial_args, **partial_kwargs)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/worker.py", line 226, in _process_task
nautobot-celery     req.execute_using_pool(self.pool)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/worker/request.py", line 707, in execute_using_pool
nautobot-celery     result = apply_async(
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/concurrency/base.py", line 152, in apply_async
nautobot-celery     return self.on_apply(target, args, kwargs,
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/billiard/pool.py", line 1530, in apply_async
nautobot-celery     self._quick_put((TASK, (result._job, None, func, args, kwds)))
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 866, in send_job
nautobot-celery     body = dumps(tup, protocol=protocol)
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/utils.py", line 525, in __getstate__
nautobot-celery     return self.nautobot_serialize()
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/utils.py", line 501, in nautobot_serialize
nautobot-celery     data["_user_pk"] = data.pop("user").pk
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 246, in inner
nautobot-celery     self._setup()
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 382, in _setup
nautobot-celery     self._wrapped = self._setupfunc()
nautobot-celery   File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/utils.py", line 482, in _get_user
nautobot-celery     self._cached_user = User.objects.get(pk=self._user_pk)
nautobot-celery AttributeError: 'NautobotFakeRequest' object has no attribute '_user_pk'
```

**Comment by gsnider2195** [comment]
Looking at a diff in a `ScheduledJob` created in v1.5.1 and one created in v1.5.8 it looks like the `ScheduledJob.kwargs["request"]["user"]` field needs to be migrated to `ScheduledJob.kwargs["request"]["_user_pk"]`. Confirmed in dev environment that this resolves the problem and allows the scheduled job to run:

```py
>>> sj=ScheduledJob.objects.first()
>>> sj.kwargs["request"]["user"]
'36ce0e2b-008e-4f18-908f-62f6ba8ef30a'
>>> sj.kwargs["request"]["_user_pk"] = sj.kwargs["request"]["user"]
>>> sj.save()
>>> sj.kwargs["request"]["_user_pk"]
'36ce0e2b-008e-4f18-908f-62f6ba8ef30a'
>>> from nautobot.core.celery import app
>>> app.control.purge()
```

**Comment by gsnider2195** [comment]
[scheduledjob_1.5.8_new.txt](https://github.com/nautobot/nautobot/files/10510658/scheduledjob_1.5.8_new.txt)
[scheduledjob_1.5.1.txt](https://github.com/nautobot/nautobot/files/10510660/scheduledjob_1.5.1.txt)

**Comment by glennmatthews** [comment]
Is deleting and re-scheduling the scheduled job(s) after the upgrade a valid workaround until we can fix this?

**Comment by gsnider2195** [comment]
That is a valid workaround. The new `ScheduledJob` gets created with the correct `_user_pk` key. However if a job makes it into the redis queue with the old key you'll have to purge the job before your workers can be restarted.
