### ISSUE TITLE
Issue adding new devices due to Attribute Error 'NoneType' object has no attribute 'location' (Possible Regression of #7792)

### ISSUE THREAD

**Issue by gneville-ot** [nautobot/nautobot#8407]
### Environment
* Nautobot version (Docker tag too if applicable): 3.0.2
* Python version: 3.12
* Database platform, version: Postgres 15
* Middleware(s): N/A

### Steps to Reproduce
1. Attempt to add a new device using SSoT that is passing 'cluster__name: None', for example:

```
+ SPARESNNUMBER123
  + face:
  + tags: []
  + serial: SPARESNNUMBER123
  + comments:
  + position: None
  + rack__name: None
  + role__name: Network Device - Spare
  + vc_position: None
  + status__name: Inventory
  + tenant__name: NetOps
  + cluster__name: None
  + location__name: Our Data Center
  + platform__name: None
  + primary_ip4__host: None
  + device_type__model: our_device_model
  + secrets_group__name: None
  + rack__location__name: None
  + virtual_chassis__name: None
  + primary_ip4__mask_length: None
  + virtual_chassis__master__name: None
  + controller_managed_device_group__name: None
```

### Expected Behavior

The device is added.

### Observed Behavior

A traceback occurs

```
celery_worker-1  |   File "/opt/nautobot/git/dcim_data_ssot/jobs/diffsync/models/devices/models.py", line 327, in create
celery_worker-1  |     new_device.validated_save()
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/models/__init__.py", line 158, in validated_save
celery_worker-1  |     self.full_clean()
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1477, in full_clean
celery_worker-1  |     self.clean()
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/validators.py", line 24, in wrapper
celery_worker-1  |     model_clean_func(model_instance)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/dcim/models/devices.py", line 860, in clean
celery_worker-1  |     if cluster.location is not None and cluster.location not in self.location.ancestors(include_self=True):
celery_worker-1  |        ^^^^^^^^^^^^^^^^
celery_worker-1  | AttributeError: 'NoneType' object has no attribute 'location'
```

**Comment by gneville-ot** [comment]
This relates to Slack Convo: https://networktocode.slack.com/archives/C01NWPK6WHL/p1767982333878909

This previously worked with nautobot version 2.4.19 and is now showing as an error when the instance was upgraded to 3.0.2

**Comment by glennmatthews** [comment]
Thanks for filing the issue. As you noted in Slack:

> Should the new code from line 860 of [nautobot/dcim/models/devices.py ](https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/models/devices.py#L860)actually be checking for the value of cluster is not None first? It feels like there is a logic error?
