### PR TITLE
added jobs migration docs

### PR DESCRIPTION
**Pull request by gsnider2195**
# Closes: #3940
# What's Changed

- Added Jobs migration docs
- Updated `JOBS_ROOT` Jobs import code to check for conflicts with existing package names
- Fixed missing Git Repository link in docs nav

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

File: nautobot/docs/additional-features/jobs.md [hunk 1]
```diff
@@ -508,7 +513,7 @@ class MyJob(Job):
 ### Accessing User and Job Result
 
 +/- 2.0.0
-    The web request is no longer accessible to running jobs.
+    The `request` property has been changed to a celery request instead of a Django web request and no longer includes the information from the web request that initiated the Job. The `user` object is now available as `self.user` instead of `self.request.user`.
```
Comment (glennmatthews) [inline nautobot/docs/additional-features/jobs.md:516]:
```suggestion
    The `request` property has been changed to a Celery request instead of a Django web request and no longer includes the information from the web request that initiated the Job. The `user` object is now available as `self.user` instead of `self.request.user`.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+
+[`self.job_result` should no longer be modified or saved from within a Job](#job_result)
+
+[Jobs must be registered in the celery task registry](#job-registration)
+
+[`self.failed` removed](#tracking-job-state)
+
+[The job logging methods have been renamed and their signature changed](#job-logging)
+
+[The `request` property has been changed to a celery request instead of a Django request](#request-property)
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:19]: Should this be a bullet list instead of a series of paragraphs?

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+
+## Overview
+
+Some fundamental changes were made to Jobs in Nautobot v2.0. This document outlines the changes that were made and how to migrate your existing Jobs to work in Nautobot v2.0. For more information about the changes made to the Job class and Job model in Nautobot v2.0 see the [Upgrading From Nautobot v1](../installation/upgrading-from-nautobot-v1.md#job-changes) documentation.
+
+### Job Package Names
+
+All Jobs are now imported as normal Python packages instead of virtually imported which means that Job file code can be shared with other Jobs or Python modules.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:27]:
```suggestion
All Jobs are now imported as normal Python packages, instead of virtually imported, which means that Job file code can be shared with other Jobs or Python modules.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+
+!!! important
+    As a result of these changes, the `JOBS_ROOT` directory and all Git Repository top level directories must now contain an `__init__.py` file.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:30]: Probably should document this in the `JOBS_ROOT` config documentation and the GitRepository model documentation.

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+
+#### App Provided Jobs
+
+The package name for Jobs provided by Nautobot Apps will not change.
+
+#### Jobs in `JOBS_ROOT`
+
+[`JOBS_ROOT`](../configuration/optional-settings.md#jobs_root) is added to `sys.path` and all modules in that directory will be imported. The package name for Jobs in `JOBS_ROOT` will be `<job_file>`, where `<job_file>` is the name of the Job file without the `.py` extension. If desired, submodules may be used in `JOBS_ROOT` like any normal Python package. For example, a Job class called `AddJob` in `$JOBS_ROOT/my_jobs/math.py` would be imported as `my_jobs.math.AddJob`.
+
+!!! note
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:40]:
```suggestion
!!! caution
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+### Job Package Names
+
+All Jobs are now imported as normal Python packages instead of virtually imported which means that Job file code can be shared with other Jobs or Python modules.
+
+!!! important
+    As a result of these changes, the `JOBS_ROOT` directory and all Git Repository top level directories must now contain an `__init__.py` file.
+
+#### App Provided Jobs
+
+The package name for Jobs provided by Nautobot Apps will not change.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:34]:
```suggestion
The package name for Jobs provided by Nautobot Apps has not changed.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+#### Jobs in `JOBS_ROOT`
+
+[`JOBS_ROOT`](../configuration/optional-settings.md#jobs_root) is added to `sys.path` and all modules in that directory will be imported. The package name for Jobs in `JOBS_ROOT` will be `<job_file>`, where `<job_file>` is the name of the Job file without the `.py` extension. If desired, submodules may be used in `JOBS_ROOT` like any normal Python package. For example, a Job class called `AddJob` in `$JOBS_ROOT/my_jobs/math.py` would be imported as `my_jobs.math.AddJob`.
+
+!!! note
+    Take care to avoid naming collisions with existing Python packages when naming Job files in `JOBS_ROOT`.
+
+#### Git Repository Jobs
+
+The package name for Jobs provided by [Git Repositories](../models/extras/gitrepository.md) will be `<git_repository_slug>.jobs`, where `<git_repository_slug>` is the slug of the Git Repository as provided by the user when creating the Git Repository object in Nautobot. All jobs provided by Git Repositories must use the `.jobs` submodule of the Git Repository.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:45]:
```suggestion
The package name for Jobs provided by [Git Repositories](../models/extras/gitrepository.md) has changed to `<git_repository_slug>.jobs`, where `<git_repository_slug>` is the slug of the Git Repository as provided by the user when creating the Git Repository object in Nautobot. All jobs provided by Git Repositories must use the `.jobs` submodule of the Git Repository.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 8]
```diff
@@ -0,0 +1,157 @@
...
+        a = IntegerVar()
+        b = IntegerVar()
+
+        def run(self, a, b):
+            return a + b
+    ```
+
+### `test_*` and `post_run()` Methods
+
+The `test_*` and `post_run` methods for backwards compatibility to NetBox scripts and reports were removed. Celery implements `before_start`, `on_success`, `on_retry`, `on_failure`, and `after_return` methods that can be used by job authors to perform similar functions.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:72]:
```suggestion
The `test_*` and `post_run` methods, previously provided for backwards compatibility to NetBox scripts and reports, have been removed. Celery implements `before_start`, `on_success`, `on_retry`, `on_failure`, and `after_return` methods that can be used by Job authors to perform similar functions.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 9]
```diff
@@ -0,0 +1,157 @@
...
+
+!!! important
+    Be sure to call the `super()` method when overloading any of the job's `before_start`, `on_success`, `on_retry`, `on_failure`, or `after_return` methods
+
+### Database Transaction Handling
+
+Jobs no longer run in an atomic database transaction by default. If a Job needs to run in a database transaction, you can use the `@transaction.atomic` decorator on the `run()` method or wrap parts of your Job code in the `with transaction.atomic()` context manager.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:79]:
```suggestion
Jobs no longer run in a single atomic [database transaction](https://docs.djangoproject.com/en/stable/topics/db/transactions/) by default. If a Job needs to run in a database transaction, you can use the `@transaction.atomic` decorator on the `run()` method or wrap parts of your Job code in the `with transaction.atomic()` context manager.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 10]
```diff
@@ -0,0 +1,157 @@
...
+
+        @transaction.atomic
+        def run(self, device_type, u_height):
+            device_type.u_height = u_height
+            device_type.save()
+    ```
+
+#### Commit Argument
+
+As a result of the default database transaction being removed from Nautobot core, the `commit` argument has been removed. If a Job author wants to provide users the ability to bypass approval when `approval_required` is set, the Job must implement a `dryrun` variable using the newly introduced `DryRunVar`. The desired value of the variable will be passed to the run method just like any other variable but the Job author must implement the logic to handle the dryrun.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:99]:
```suggestion
As a result of the default database transaction being removed from Nautobot core, the `commit` argument has been removed. If a Job author wants to provide users the ability to bypass approval when `approval_required` is set, the Job must implement a `dryrun` variable using the newly introduced `DryRunVar`. The desired value of the variable will be passed to the `run` method just like any other variable, but the Job author must implement the logic to handle the dryrun.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 11]
```diff
@@ -0,0 +1,157 @@
...
+
+The presence of a `dryrun = DryRunVar()` property on the Job class sets the `supports_dryrun` flag on the Job model, which allows users to bypass approval when `approval_required` is set. To implement a dryrun variable without allowing users to bypass approval, the `dryrun` variable should use the `BooleanVar` class instead of `DryRunVar`.
+
+The Job `commit_default` property has been renamed to `dryrun_default` and the default value as well as any existing database values have been flipped.
+
+#### Read-Only Meta Attribute
+
+The `read_only` Job field no longer changes the behavior of Nautobot core and is informational only in v2.0.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:107]:
```suggestion
The `read_only` Job field no longer forces an automatic database rollback at the end of the Job; it is informational only in v2.0.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 12]
```diff
@@ -0,0 +1,157 @@
...
+
+### Job Registration
+
+All Jobs must be registered in the celery task registry to be available in Nautobot. This must be accomplished by calling `nautobot.core.celery.register_jobs(*job_classes)` at the top level of a Job module so that it is registered when the module is imported. The `register_jobs` method accepts one or more job classes as arguments.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:111]:
```suggestion
All Jobs must be registered in the Celery task registry to be available in Nautobot. This must be accomplished by calling `nautobot.core.celery.register_jobs(*job_classes)` at the top level of a Job module so that it is registered when the module is imported. The `register_jobs` method accepts one or more job classes as arguments.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 13]
```diff
@@ -0,0 +1,157 @@
...
+
+* `logger.debug("message", extra={"skip_db_logging": True})` - Log the message to the console but not to the database
+* `logger.debug("message", extra={"object": obj})` - Replaces the `obj` kwarg in Nautobot v1.X Job logging methods
+* `logger.debug("message", extra={"grouping": "string"})` - Replaces the `active_test` Job property in Nautobot v1.X
+
+For more detailed documentation on Job logging see the [Job Logging](../additional-features/jobs.md#logging) section of the Jobs feature documentation.
+
+### Tracking Job State
+
+`JobResult.status` is now automatically tracked by celery. Job authors should no longer manually change `self.job_result.status` or `self.job_result.completed` and should instead raise an exception if the Job status should be set to failed (the failed status is now `"FAILURE"`).
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:151]:
```suggestion
`JobResult.status` is now automatically tracked by Celery. Job authors should no longer manually change `self.job_result.status` or `self.job_result.completed` and should instead raise an exception if the Job status should be set to failed (the failed status is now `"FAILURE"`).
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 14]
```diff
@@ -0,0 +1,157 @@
...
+
+The Job's `self.failed` flag that was used to determine if a Job failed has been removed. This flag was set to `True` when the `log_failure` method was called. Job authors should track their Job's internal state and raise an exception to fail the Job.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:153]:
```suggestion
The Job's built-in`self.failed` flag, that was used to determine if a Job failed, has been removed. This flag was previously set to `True` automatically when the `log_failure` method was called. Job authors should track their Job's internal state and raise an exception to fail the Job when desired.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 15]
```diff
@@ -0,0 +1,157 @@
...
+
+### Request Property
+
+The `request` property has been changed to a celery request instead of a Django request and no longer includes the information from the web request that initiated the Job. The `user` object is now available as `self.user` instead of `self.request.user`.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:157]:
```suggestion
The `request` property has been changed to a Celery request instead of a Django request and no longer includes the information from the web request that initiated the Job. The `user` object is now available as `self.user` instead of `self.request.user`.
```

File: nautobot/docs/installation/upgrading-from-nautobot-v1.md [hunk 16]
```diff
@@ -347,3 +352,7 @@ The `commit_default` job field has been renamed to `dryrun_default` and the defa
 
 !!! important
     Nautobot no longer enforces any job behavior when dryrun is set. It is now the job author's responsibility to define and enforce the execution of a "dry run".
+
+### Request Property
+
+The `request` property has been changed to a celery request instead of a Django web request and no longer includes the information from the web request that initiated the Job. The `user` object is now available as `self.user` instead of `self.request.user`.
```
Comment (glennmatthews) [inline nautobot/docs/installation/upgrading-from-nautobot-v1.md:358]:
```suggestion
The `request` property has been changed to a Celery request instead of a Django web request and no longer includes the information from the web request that initiated the Job. The `user` object is now available as `self.user` instead of `self.request.user`.
```

File: nautobot/extras/test_jobs/job_button_receiver.py [hunk 17]
```diff
@@ -8,13 +8,13 @@
 
 class TestJobButtonReceiverSimple(JobButtonReceiver):
     def receive_job_button(self, obj):
-        logger.info("request.user: %s", self.request.user.username)
+        logger.info("user: %s", self.user.username)
```
Comment (glennmatthews) [inline nautobot/extras/test_jobs/job_button_receiver.py:11]: Huh. Why weren't these erroring out before?

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md (hunk 10 above)
Comment (jathanism) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:99]:
```suggestion
As a result of the default database transaction being removed from Nautobot core, the `commit` argument has been removed. If a Job author wants to provide users the ability to bypass approval when `approval_required` is set, the Job must implement a `dryrun` variable using the newly-introduced `DryRunVar`. The desired value of the variable will be passed to the run method just like any other variable but the Job author must implement the logic to handle the dry run.
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 18]
```diff
@@ -0,0 +1,157 @@
...
+        def run(self, device_type, u_height):
+            device_type.u_height = u_height
+            device_type.save()
+    ```
+
+#### Commit Argument
+
+As a result of the default database transaction being removed from Nautobot core, the `commit` argument has been removed. If a Job author wants to provide users the ability to bypass approval when `approval_required` is set, the Job must implement a `dryrun` variable using the newly introduced `DryRunVar`. The desired value of the variable will be passed to the run method just like any other variable but the Job author must implement the logic to handle the dryrun.
+
+The presence of a `dryrun = DryRunVar()` property on the Job class sets the `supports_dryrun` flag on the Job model, which allows users to bypass approval when `approval_required` is set. To implement a dryrun variable without allowing users to bypass approval, the `dryrun` variable should use the `BooleanVar` class instead of `DryRunVar`.
```
Comment (jathanism) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:101]:
```suggestion
The presence of a `dryrun = DryRunVar()` property on the Job class sets the `supports_dryrun` flag on the Job model, which allows users to bypass approval when `approval_required` is set. To implement a dry run variable without allowing users to bypass approval, the `dryrun` variable should use the `BooleanVar` class instead of `DryRunVar`.
```

**Review by jathanism — CHANGES_REQUESTED** [review]
All plain language references to "dryrun" should be "dry run". As a variable it's fine to leave it as-is.

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md (hunk 4 above)
Comment (gsnider2195) [reply nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:30]: `JOBS_ROOT` already needed it (and was documented) so I removed it here. I made some tweaks to the git repo doc while I was in there adding this.

File: nautobot/extras/test_jobs/job_button_receiver.py (hunk 17 above)
Comment (gsnider2195) [reply nautobot/extras/test_jobs/job_button_receiver.py:11]: It appears there are no tests actually exercising this code. I tested a job to verify this shouldn't work:

```
(Pdb) self.user
<User: test-user>
(Pdb) self.request
<Context: {'id': '8fea3f57-273d-48bb-a5e0-31e4f7a61e75', 'retries': 0, 'is_eager': True, 'logfile': None, 'loglevel': 0, 'hostname': 'ac294c577bc0', 'callbacks': None, 'errbacks': None, 'headers': None, 'ignore_result': False, 'delivery_info': {'is_eager': True, 'exchange': None, 'routing_key': None, 'priority': None}, 'properties': {'nautobot_job_job_model_id': UUID('fc216cc7-174c-49f2-8af1-29f8ee262621'), 'nautobot_job_profile': False, 'nautobot_job_user_id': UUID('0cfeb801-abaf-421a-95b6-457466d418f9'), 'queue': 'default'}, 'args': (), 'called_directly': False, 'kwargs': {}}>
(Pdb) self.request.user
*** AttributeError: 'Context' object has no attribute 'user'
```

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 19]
```diff
@@ -0,0 +1,150 @@
...
+## Overview
+
+Some fundamental changes were made to Jobs in Nautobot v2.0. This document outlines the changes that were made and how to migrate your existing Jobs to work in Nautobot v2.0. For more information about the changes made to the Job class and Job model in Nautobot v2.0 see the [Upgrading From Nautobot v1](../installation/upgrading-from-nautobot-v1.md#job-changes) documentation.
+
+### Job Package Names
+
+All Jobs are now imported as normal Python packages, instead of virtually imported, which means that Job file code can be shared with other Jobs or Python modules.
+
+!!! important
+    As a result of these changes all Git Repository top level directories must now contain an `__init__.py` file.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:23]:
```suggestion
    As a result of these changes the top-level directory of any Git Repository that provides Jobs must now contain an `__init__.py` file.
```

Comment (glennmatthews) [reply nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:23]: Should this note move under the `Git Repository Jobs` subhead?

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md [hunk 20]
```diff
@@ -0,0 +1,150 @@
...
+
+As a result of the default database transaction being removed from Nautobot core, the `commit` argument has been removed. If a Job author wants to provide users the ability to bypass approval when `approval_required` is set, the Job must implement a `dryrun` variable using the newly-introduced `DryRunVar`. The desired value of the variable will be passed to the `run` method just like any other variable, but the Job author must implement the logic to handle the dry run.
+
+The presence of a `dryrun = DryRunVar()` property on the Job class sets the `supports_dryrun` flag on the Job model, which allows users to bypass approval when `approval_required` is set. To implement a dry run variable without allowing users to bypass approval, the `dryrun` variable should use the `BooleanVar` class instead of `DryRunVar`.
+
+The Job `commit_default` property has been renamed to `dryrun_default` and the default value as well as any existing database values have been flipped.
+
+#### Read-Only Meta Attribute
+
+The `read_only` Job field no longer forces an automatic database rollback at the end of the Job; it is informational only in v2.0.
```
Comment (glennmatthews) [inline nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:100]: Does it have any influence on Job approval requirements/behavior?

File: nautobot/docs/models/extras/gitrepository.md [hunk 21]
```diff
@@ -40,15 +40,18 @@ Whenever a Git repository record is created, updated, or deleted, Nautobot autom
 
 ## Repository Structure
 
++/- 2.0.0
+    Git Repositories are now imported as standard Python packages and therefore all Git Repository top level directories must now contain an `__init__.py` file.
```
Comment (glennmatthews) [inline nautobot/docs/models/extras/gitrepository.md:44]: Probably good to reword this and/or merge it with the below 2.0.0 note to make it clearer that this is only a behavior/requirement if your Git repository provides Jobs.

**Review by glennmatthews — APPROVED** [review]

**Review by jathanism — APPROVED** [review]

File: nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md (hunk 20 above)
Comment (gsnider2195) [reply nautobot/docs/apps/migrating-jobs-from-nautobot-v1.md:100]: Not as of 2.0
