### ISSUE TITLE
Apps with view overrides crash nautobot on startup when upgrades from 2.2 to 2.3

### ISSUE THREAD

**Issue by pszulczewski** [nautobot/nautobot#6564]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.11
* Python version: 3.11
* Database platform, version: PostgreSQL

When upgrading Nautobot from 2.2.x to 2.3.11, apps using view overrides can not be initialized on Nautobot startup.
Sample view override:

```
override_view = {
    "circuits:circuit_list": CustomCircuitListView.as_view({'get': 'list'})
}
```

### Steps to Reproduce
1. Extend example plugin with override_view like given above.
2. Start Nautobot

### Expected Behavior
Nautobot starts and initializes an app overriding view.

### Observed Behavior

Exception on startup:
```
(qualified_view_name, f"{view.__module__}.{view.view_class.__name__}")
AttributeError: 'function' object has no attribute 'view_class'
```

**Comment by pszulczewski** [comment]
You can switch to `fix-6564` branch where I added view_overrides to example_app. This does not effectively override anything and it's only for registering an override.

Just run `invoke unittest -s` and you'll see:
```
Traceback (most recent call last):
  File "/source/nautobot/core/cli/__main__.py", line 3, in <module>
    main()
  File "/source/nautobot/core/cli/__init__.py", line 293, in main
    execute_from_command_line([sys.argv[0], *unparsed_args])
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/source/examples/example_app/example_app/__init__.py", line 43, in ready
    super().ready()
  File "/source/nautobot/extras/plugins/__init__.py", line 211, in ready
    (qualified_view_name, f"{view.__module__}.{view.view_class.__name__}")
AttributeError: 'function' object has no attribute 'view_class'
```

**Comment by glennmatthews** [comment]
Thanks! Probably need some logic to distinguish between `View` versus `NautobotUIViewSet` behavior, similar to https://github.com/nautobot/nautobot/blob/d422cb4b9cd11fb80066838fe6e65a53c98c2ed8/nautobot/core/views/__init__.py#L308-L309

**Comment by pszulczewski** [comment]
It can be fixed with the commit above, but I am not sure if that covers all possible scenarios. Maybe we need to check on subclass rather than blindly fallback to `.cls.__name__` when `view_class` attr is not present.

**Comment by glennmatthews** [comment]
That *should* at least address both common view patterns. I'd be fine with you opening a PR with the current commit.
