### ISSUE TITLE
[1.6] InterfaceRedundancyGroupAssociation CustomField

### ISSUE THREAD

**Issue by milan2655** [nautobot/nautobot#4797]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.4
* Python version: 3.11.6
* Database platform, version: PG13
* Middleware(s):

### Steps to Reproduce
1. create custom field: `dcim | interface redundancy group association`
2. retrieve CF from InterfaceRedundancyGroupAssociation object

### Expected Behavior
```
>>>  InterfaceRedundancyGroupAssociation.objects.first().cf
{}
```

### Observed Behavior
```
>>> InterfaceRedundancyGroupAssociation.objects.first().cf
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'InterfaceRedundancyGroupAssociation' object has no attribute 'cf'
```

**Comment by glennmatthews** [comment]
Interesting. `InterfaceRedundancyGroupAssociation` model doesn't support custom fields, and I don't see `dcim | interface redundancy group association` as an option when defining a Custom Field in the UI. How did you create the custom field?

**Comment by milan2655** [comment]
![Screenshot 2023-11-14 at 15 05 40](https://github.com/nautobot/nautobot/assets/61010723/c0ad2d43-cb07-4db2-8f58-c66980c082dd)

**Comment by glennmatthews** [comment]
Ah thanks. I was testing in 2.0 rather than 1.6; it looks like the option to define them was removed as a side effect of some of the other changes we've made in 2.0.

**Comment by lampwins** [comment]
A bit of context... these many-to-many association through models are a newer pattern for us and we haven't yet considered how to make them first class citizens, in terms of things like extensibility feature sets. This undoubtedly leads to some of the inconsistency, for example, being able to declare a field, despite `_custom_field_data` not actually existing on the model.

I think the configuration management use cases surrounding these models do provide a compelling reason to enable all of the extensibility features, plus the basic fact that the reason we wanted an explicit through model is because we need more context to be a part of the M2M association.

Unfortunately, making custom fields work in 1.6 is going to be a non-starter because it would entail a schema migration. We can however, look to do this in the mainline 2.X releases.

That said, we will continue to treat this issue as a bug, in that you should not see this model as an option in 1.6.

**Comment by glennmatthews** [comment]
implemented for 1.6 by #4878.
